/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GriffeModel(props) {
  const { nodes, materials } = useGLTF("/griffe-symbole.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.MiddleLIne}
        rotation={[-1.57, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials.Taurus}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.001"]}
        position={[0.3, -0.37, 0]}
        rotation={[1.57, -0.85, -1.57]}
        scale={[1, 0.49, 0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.002"]}
        position={[-0.3, -0.37, 0]}
        rotation={[1.57, 0.85, 1.57]}
        scale={[1, 0.49, 0.82]}
      />
    </group>
  );
}

useGLTF.preload("/griffe-symbole.glb");


