import Head from "next/head";
import styled from "styled-components";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";
import CardsComponent from "../components/cards.component";


export default function Home() {

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Les PNJs dans Atozia </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <CardsComponent />


        <footer className={styles.footer}>Powered by Atozia Familly</footer>
      </div>
    </Layout>
  );
}
