import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import CardsComponent from "../components/cards.component";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

const Intro = styled.main`
  padding: 4rem 0;
  margin-bottom: 10rem;
`;

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Les PNJs dans Atozia </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Link href="/game">Jouer</Link>
        <Intro>
<<<<<<< HEAD
          <h1>Pour un petit plaisir atozien</h1>
          {/* <Link href="/cards">Les cartes</Link> */}
=======
          <h1 className={styles.title}>Pour un petit plaisir atozien</h1>
>>>>>>> 8e9331f (Set the multiplayer)
        </Intro>

        <CardsComponent />
        <footer className={styles.footer}>Powered by Atozia Familly</footer>
      </div>
    </Layout>
  );
}
