import styledComponents from "styled-components";
import Layout from "../components/layout";

const HistoryWrapper = styledComponents.div`
    max-width: 80ch;
    padding: 4rem 0;
`;

const Content = styledComponents.div`
`;

const SpecialWords = styledComponents.span`
    font-weight: bold;
    color: #F645A0
`;

export default function Sultanat() {
  return (
    <Layout>
      <HistoryWrapper>
        <h1>Le Sultanat, par Hek Alzir</h1>
            <Content>
            <p>Il y a, en Aod, de nombreuses entit&eacute;s puissantes, une grande quantit&eacute; de richesses vari&eacute;es et de nombreuses cit&eacute;s, dont certaines particuli&egrave;rement grandes. Le royaume de Danherad, par exemple, est le plus vaste et le plus peupl&eacute; des royaumes et vous en entendrez parler partout dans l&rsquo;Aod. Cependant dans ce monde, c&rsquo;est Ellan Zar qui, certes en tant que seule cit&eacute; du Sultanat, est de loin la cit&eacute; la plus peupl&eacute;e et le plus grand carrefour commercial de l&rsquo;Aod. Le Sultana forge sa r&eacute;putation depuis des si&egrave;cles et exerce sur l&rsquo;Aod une influence puissante et redout&eacute;e.</p>

<p>Ne voyez aucune vanit&eacute; dans mes propos, il est important que vous sachiez cela car, en devenant Pesoh, vous b&eacute;n&eacute;ficiez de l&rsquo;avantage d&rsquo;une telle position mais aussi des responsabilit&eacute;s qui vont avec. Vous agirez avec les ressources nombreuses et vari&eacute;es du Sultanat mais vous devrez &eacute;galement suivre ses r&egrave;gles sur son sol et aupr&egrave;s du reste de l&rsquo;Aod.</p>

<p>Vous d&eacute;couvrirez le Sultanat par vous-m&ecirc;me et je serais l&agrave; pour vous guider et vous accompagner, n&eacute;anmoins je me permets de pr&eacute;ciser d&egrave;s &agrave; pr&eacute;sent quelques informations. (Il inspire et laisse un silence pr&eacute;c&eacute;der ses mots, en mode genre je me la p&egrave;te, ou pas.). Il y a deux autorit&eacute;s au Sultanat, le Sultan et l&rsquo;Ordre des Kirkshen, terme difficilement traduisible&#8230; peut-&ecirc;tre par Filles du d&eacute;sert, mais &eacute;galement gardienne du d&eacute;sert ou m&ecirc;me&#8230; lectrice du d&eacute;sert.</p>

<p>Le Sultan dirige le Sultanat et a pour mission principale de le prot&eacute;ger de l'ext&eacute;rieur, de garantir la paix &agrave; l&rsquo;int&eacute;rieur et de s&rsquo;assurer qu&rsquo;il dure dans le temps. Le Sultan a la possession de la couleur noire au sein du Sultanat. Nul ne peut la rev&ecirc;tir sans son accord, &agrave; l&rsquo;exception de quelques objets qui ne doivent pas comporter de symbole et de quelques parties de v&ecirc;tements dont ce n&rsquo;est pas la couleur principale. Cette couleur, en plus d&rsquo;&ecirc;tre rare, est g&eacute;n&eacute;ralement &eacute;vit&eacute;e. Je dois vous pr&eacute;ciser ici que le Sultanat s&rsquo;appuie plus sur la qualit&eacute; que la quantit&eacute; dans de nombreux domaines. Il poss&egrave;de ainsi des miliciens et des hommes d&rsquo;armes pour effectuer certaines t&acirc;ches, comme ceux qui m&rsquo;ont accompagn&eacute; mais qui ont malheureusement p&eacute;ri (il accompagne ces propos d&rsquo;un geste de la main c&eacute;r&eacute;moniel en direction du soleil, geste qu&rsquo;ils utilisent avec Shaadi &agrave; chaque fois qu&rsquo;ils parlent d&rsquo;un proche d&eacute;c&eacute;d&eacute;.(Et la GE est g&eacute;n&eacute;reuse dans le domaine)), cependant dans chaque domaine, le Sultana s&rsquo;&eacute;vertue &agrave; former des agents ou soldats d&rsquo;&eacute;lite, leur accordant toutes les ressources n&eacute;cessaires pour les rendre le plus qualifi&eacute; et comp&eacute;tent possible, ce sont ces derniers qui portent le noir (au passage le Hek est en noir int&eacute;grale). Cette politique s&rsquo;accorde avec les particularit&eacute;s du Sultanat mais permet aussi d'asseoir une r&eacute;putation de qualit&eacute; et d&rsquo;efficacit&eacute; r&eacute;pandue dans tout l&rsquo;Aod depuis plusieurs si&egrave;cle. Le port du noir int&eacute;grale est reconnu dans tout l&rsquo;Aod comme un symbole fort du Sultanat. Cela s&rsquo;&eacute;tend jusqu&rsquo;&agrave; la flotte o&ugrave; les navires arborant une voile noire, teinte que seuls les ressources du d&eacute;sert peuvent fournir en de telles quantit&eacute;s, sont des navires craints sur toutes les mers.</p>

<p>Dans sa d&eacute;fense du Sultanat vers l&rsquo;ext&eacute;rieur, le Sultan, comme ses pr&eacute;d&eacute;cesseurs, appliquent une justice ferme et rapide. Ainsi &agrave; l&rsquo;exception des quartiers des Natvorhil, tout Natvoron p&eacute;n&eacute;trant sans autorisation sur le territoire du Sultanat est ex&eacute;cut&eacute;. Tout capitaine de navire ayant achemin&eacute; un Natvoron sur le territoire, m&ecirc;me &agrave; son insu, est ex&eacute;cut&eacute;. Tout Pesoh mettant en p&eacute;ril d&rsquo;une mani&egrave;re ou d&rsquo;une autre la s&eacute;curit&eacute; des habitants d&rsquo;Ellan Zar est ex&eacute;cut&eacute;.</p>

<p>Le Sultana fait peu de Natvoron prisonnier, uniquement si des informations doivent leur &ecirc;tre soutir&eacute;s.</p>

<p>L&rsquo;Ordre des Kirkshen, quant &agrave; lui, a de nombreuses missions au sein du d&eacute;sert mais aussi au sein d&rsquo;Ellan Zar, les Kirkshen ont pour mission de pr&eacute;server les traditions du Sultanat, de s&rsquo;occuper et de prot&eacute;ger les Pesoh. Concr&egrave;tement, cela va se traduire par les soins de toute sorte, y compris ceux concernant l&rsquo;esprit, la mise au monde des b&eacute;b&eacute;s, les rites mortuaires, l&rsquo;&eacute;ducation, l&rsquo;entretien des Kasan et &eacute;ventuellement des Kasan-Deh, s&rsquo;appuyant sur des savoirs-faires demeurant secrets. L&rsquo;Ordre des Kirkshen a la possession de la couleur jaune int&eacute;grale au sein du Sultana, bien que cette derni&egrave;re soit tol&eacute;r&eacute;e en moindre proportion sur des ensembles de couleurs sur des v&ecirc;tements. Vous les rep&egrave;rerez vite au sein de la cit&eacute;, arborant ce jaune vif et poss&eacute;dant sur le front des signes blancs indiquant leur statut et leur rang au sein de l&rsquo;Ordre. Les Kirkshens sont tr&egrave;s majoritairement des femmes mais certains hommes int&egrave;grent l&rsquo;Ordre en tant que combattant afin que l&rsquo;Ordre puisse se prot&eacute;ger, notamment dans le d&eacute;sert. C&rsquo;&eacute;tait le cas de celui qui &eacute;tait mon ami et celui de Shaadi, Azad (&agrave; nouveau le geste vers le soleil).</p>

<p>Une derni&egrave;re couleur est poss&eacute;d&eacute;e, dans une bien moindre mesure car elle est port&eacute;e en uniforme avec des grades et des symboles noirs sur les &eacute;paules par tous les agents qui s&rsquo;assurent &eacute;galement du bien-&ecirc;tre quotidien de la cit&eacute;. Il s&rsquo;agit du gris int&eacute;gral, que portent les miliciens, les collecteurs de la Jerh, les collecteurs d&rsquo;ordures, les juges d&rsquo;habitat et les passeurs au sein de la baie d&rsquo;Ellan Zar. Vous pouvez n&eacute;anmoins &ecirc;tre v&ecirc;tu de gris tant qu&rsquo;il n&rsquo;y a pas de symbole noir sur les &eacute;paules. Chacun de ces corps de m&eacute;tiers &agrave; un responsable qui r&eacute;pond &agrave; un Vizir Gris.</p>

<p>Autre particularit&eacute; que nous ne retrouvons pas ailleurs en Aod ni dans vos contr&eacute;es, &agrave; ma connaissance. Il n&rsquo;y a pas d&rsquo;h&eacute;ritage au sein du Sultana. Un homme ou un couple, car une femme seule ne peut avoir une demeure &agrave; soi, peuvent poss&eacute;der une demeure mais &agrave; leur mort, elle est remise en vente sur le march&eacute;, bien que de coutumes si l&rsquo;un des enfants peut payer, il a officieusement une priorit&eacute;. De plus, la fortune ou les titres ne sont pas transmis. Ainsi les pr&eacute;tentions de chacun ne d&eacute;pendent pas de leurs anc&ecirc;tres. Bien entendu une bonne situation accompagn&eacute;e d&rsquo;une bonne &eacute;ducation et d&rsquo;un bon r&eacute;seau de connaissance ne rendent pas les choses &eacute;quitables, n&eacute;anmoins l&rsquo;inertie est bien moins forte et les possibilit&eacute;s d&rsquo;acc&eacute;der &agrave; un poste ou une fonction vont d&eacute;pendre principalement des capacit&eacute;s du pr&eacute;tendant. Il existe un chant ancien du Sultanat qui est l&rsquo;un des piliers de notre soci&eacute;t&eacute; et dans lequel il est notamment mentionn&eacute; que tout b&eacute;b&eacute; poussant son premier cri, entonnant son premier rire et versant sa premi&egrave;re larme sous le soleil au-dessus de ce d&eacute;sert peut jouir de la libert&eacute; totale de sa vie. Ces r&egrave;gles sont une tentative de favoriser au mieux cela.</p>

<p>Je devine l&rsquo;une de vos questions concernant le r&ocirc;le du Sultan. Il y a bien une exception sur ce sujet, le Sultan ne peut qu&rsquo;appartenir &agrave; la famille du Clan du Sultan et doit par ailleurs poss&eacute;der ce qu&rsquo;on appelle &laquo; Les yeux contenant un &eacute;clat du soleil &raquo; en adressant un bref regard en direction de Shaadi.</p>

<p>Concernant l&rsquo;organisation, le Sultan est entour&eacute; du Vizir de la Flotte, du Vizir de l&rsquo;arm&eacute;e, du Vizir Gris, que nous avons d&eacute;j&agrave; &eacute;voqu&eacute;, du Vizir de l&rsquo;information, du Vizir du d&eacute;sert, du Vizir des Natvoron et le Grand Vizir. Chaque Vizir porte le noir mais rev&ecirc;t sur le bras gauche le brassard de son titre. Hi&eacute;rarchiquement, seul l&rsquo;Ordre des Kirkshen ne r&eacute;pond pas directement ou indirectement au Sultan.</p>

<p>D&rsquo;un point de vue comportementale, enfin, il me semble n&eacute;cessaire que vous ayez connaissance du fait est que chez les Belloreks, il peut &ecirc;tre consid&eacute;rer comme insultant de courtiser une femme promise &agrave; un autre ou dont les familles sont en discussions. Pour indiquer ces phases particuli&egrave;res de leurs vies, les femmes Bellorek ne croisent pas le regard des hommes durant ces moments, afin qu&rsquo;il y ait nul malentendu. Par ailleurs, les relations amoureuses ou charnelles entre personnes du m&ecirc;me sexes ne doivent pas &ecirc;tre rendues publiques (le Hek jette un coup d&rsquo;&#339;il &agrave; Harmony). Enfin, contrairement &agrave; de nombreuses cultures en Aod, un homme ne peut avoir qu&rsquo;une seule &eacute;pouse. Toute femme n&rsquo;ayant pas trouv&eacute; d&rsquo;&eacute;poux apr&egrave;s sa dix-huiti&egrave;me ann&eacute;e et n&rsquo;exer&ccedil;ant pas une profession pour le Sultan doit int&eacute;grer les Kirkshens.</p>
            </Content>
      </HistoryWrapper>
    </Layout>
  );
}
